/*   Do *not* directly modify this file.  It was    */
/*   generated by the Configuration Tool; any  */
/*   changes risk being overwritten.                */

/* INPUT my_first_project2018.cdb */

/*  Include Header File  */
#include "my_first_project2018cfg.h"

/*  Config Structures */
/*  Handles  */
